services:
  server:
    container_name: server
    image: server
    build:
      context: .
      dockerfile: Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=5000
    ports:
      - "5000:5000"
  nginx:
    container_name: nginx
    hostname: localhost
    image: nginx
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile   
    volumes: 
      #- ./client/dist:/usr/share/nginx/html 
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf 
      #- ./.docker/nginx/proxy.conf:/etc/nginx/proxy.conf  
    ports:
      - 8080:80
    links:
      - server:server
